<?php
/**
 * ACF helper functions
 */

// change / add to the base background choices here
$base_background_options = array (
	'no-background' 		=> 'No background',
	'inverse-background' 	=> 'Inverse',
	'primary-background'	=> 'Primary color background',
);

// grab any accent colors added in the site options with ACF
$acf_color_options = array();
if( get_option( 'options_accent_colors_container_accent_color_array' ) ) :
	$number = get_option( 'options_accent_colors_container_accent_color_array' );
	for ( $i=1; $i<=(int)$number; $i++ ) {
		$acf_color_options[ 'accent-color-' . $i ] = "Accent color #" . $i;
	}
endif;

// now merge those two arrays for all the background options
$background_choices_available = array_merge( $base_background_options, $acf_color_options );


// settings on where the 'sections' are active throughout the site
$where_sections_are_active = array (
	array (
		array (
			'param' => 'post_type',
			'operator' => '==',
			'value' => 'page',
		),
	),
/*	add any additional post types here. 
	array (
		array (
			'param' => 'post_type',
			'operator' => '==',
			'value' => 'person',
		),
	),
*/
);


//***************************************   SITE OPTIONS
if( function_exists('acf_add_local_field_group') ):
acf_add_local_field_group(array (
	'key' => 'group_57f7c88c9aa18',
	'title' => 'Site Options',
	'fields' => array (
		array (
			'key' => 'field_57fbf3676e7e9',
			'label' => 'Display Options',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array(
			'key' => 'field_5a1f1b703a28e',
			'label' => 'Site Logo',
			'name' => 'site_logo',
			'type' => 'image',
			'instructions' => 'Add a logo image for the header. If none, the site name will show in large text.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'url',
			'preview_size' => 'medium',
			'library' => 'all',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => 'jpg, gif, svg, png',
		),
		array (
			'key' => 'field_57f7c92167a96',
			'label' => 'Default Featured Image',
			'name' => 'default_post_thumbnail_id',
			'type' => 'image',
			'instructions' => 'If set, this image will be displayed as the featured image for any posts that don\'t have their own custom featured images.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'id',
			'preview_size' => 'thumbnail',
			'library' => 'all',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
		),
		array (
			'key' => 'field_57fc43235c0d0',
			'label' => 'Excerpt Settings',
			'name' => '',
			'type' => 'message',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => 'Settings below determine how automatically generated post excerpts (aka blurbs) are displayed: how long they should be, and what text (if any) should be appended to the excerpt as a link to the post itself.',
			'new_lines' => 'wpautop',
			'esc_html' => 0,
		),
		array (
			'key' => 'field_57fbf44a6e7f0',
			'label' => 'Length',
			'name' => 'excerpt_length',
			'type' => 'number',
			'instructions' => 'Set to 0 to revert to WordPress\'s default (55 words), or to allow another plugin to trim excerpts.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '40',
				'class' => '',
				'id' => '',
			),
			'default_value' => 40,
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'min' => '',
			'max' => '',
			'step' => '',
		),
		array (
			'key' => 'field_57fbf4686e7f1',
			'label' => 'Units',
			'name' => 'excerpt_length_unit',
			'type' => 'radio',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '20',
				'class' => '',
				'id' => '',
			),
			'choices' => array (
				'words' => 'Words',
				'chars' => 'Characters',
			),
			'allow_null' => 0,
			'other_choice' => 0,
			'save_other_choice' => 0,
			'default_value' => 'words',
			'layout' => 'vertical',
			'return_format' => 'value',
		),
		array (
			'key' => 'field_57fc42c5a2686',
			'label' => 'Link Text',
			'name' => 'excerpt_link_text',
			'type' => 'text',
			'instructions' => 'e.g. \'Read more\'. Leave blank for no link.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '40',
				'class' => '',
				'id' => '',
			),
			'default_value' => 'Read more',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5a1dd45d5edcf',
			'label' => 'Disable page sections on regular pages',
			'name' => 'disable_sections_on_pages',
			'type' => 'true_false',
			'instructions' => 'Check this box to remove the "page sections" editing capabilities on all inside pages of the site. The sections capabilities will then only show up on the front homepage (if a static page is used for the front page) and all inside pages will use the default WordPress page editor.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '100',
				'class' => '',
				'id' => '',
			),
			'message' => 'Use the default WordPress page editor',
			'default_value' => 0,
			'ui' => 0,
			'ui_on_text' => '',
			'ui_off_text' => '',
		),
		array (
			'key' => 'field_5a1d8a764a977',
			'label' => 'Colors',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),

		array(
			'key' => 'field_5ff4c898f375b',
			'label' => 'Theme colors',
			'name' => 'design_colors',
			'type' => 'group',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layout' => 'block',
			'sub_fields' => array(
				array(
					'key' => 'field_5ff4c8fef375c',
					'label' => 'Page top color bar',
					'name' => 'page_top_color_bar',
					'type' => 'color_picker',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '100',
						'class' => '',
						'id' => '',
					),
					'default_value' => '#faec75',
				),
				array(
					'key' => 'field_5ffb8f891b2fd',
					'label' => 'Text link color',
					'name' => 'text_link_color',
					'type' => 'color_picker',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '50',
						'class' => '',
						'id' => '',
					),
					'default_value' => '#4c8df4',
				),
				array(
					'key' => 'field_5ffb8fe81b2fe',
					'label' => 'Text link hover color',
					'name' => 'text_link_hover_color',
					'type' => 'color_picker',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '50',
						'class' => '',
						'id' => '',
					),
					'default_value' => '#9546f4',
				),
				array(
					'key' => 'field_5ffb8d801b2f5',
					'label' => 'Default button background color',
					'name' => 'default_button_background_color',
					'type' => 'color_picker',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '25',
						'class' => '',
						'id' => '',
					),
					'default_value' => '#f44b83',
				),
				array(
					'key' => 'field_5ffb8db91b2f6',
					'label' => 'Default button text color',
					'name' => 'default_button_text_color',
					'type' => 'color_picker',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '25',
						'class' => '',
						'id' => '',
					),
					'default_value' => '#ffffff',
				),
				array(
					'key' => 'field_5ffb8de81b2f7',
					'label' => 'Default button hover background color',
					'name' => 'default_button_hover_background_color',
					'type' => 'color_picker',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '25',
						'class' => '',
						'id' => '',
					),
					'default_value' => '#483D31',
				),
				array(
					'key' => 'field_5ffb8e191b2f8',
					'label' => 'Default button hover text color',
					'name' => 'default_button_hover_text_color',
					'type' => 'color_picker',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '25',
						'class' => '',
						'id' => '',
					),
					'default_value' => '#ffffff',
				),
				array(
					'key' => 'field_5ffb8e4d1b2fa',
					'label' => 'Secondary button background color',
					'name' => 'secondary_button_background_color',
					'type' => 'color_picker',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '25',
						'class' => '',
						'id' => '',
					),
					'default_value' => '#BDD886',
				),
				array(
					'key' => 'field_5ffb8e361b2f9',
					'label' => 'Secondary button text color',
					'name' => 'secondary_button_text_color',
					'type' => 'color_picker',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '25',
						'class' => '',
						'id' => '',
					),
					'default_value' => '#292929',
				),
				array(
					'key' => 'field_5ffb8e971b2fb',
					'label' => 'Secondary button hover background color',
					'name' => 'secondary_button_hover_background_color',
					'type' => 'color_picker',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '25',
						'class' => '',
						'id' => '',
					),
					'default_value' => '#66CF8D',
				),
				array(
					'key' => 'field_5ffb8f4e1b2fc',
					'label' => 'Secondary button hover text color',
					'name' => 'secondary_button_hover_text_color',
					'type' => 'color_picker',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '25',
						'class' => '',
						'id' => '',
					),
					'default_value' => '#292929',
				),
				array(
					'key' => 'field_5ffb90fbad78d',
					'label' => 'Accent color - Tagline & header lines',
					'name' => 'accent_color_header',
					'type' => 'color_picker',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '50',
						'class' => '',
						'id' => '',
					),
					'default_value' => '#f44b83',
				),
				array(
					'key' => 'field_5ffb916aad78e',
					'label' => 'Accent color - Separator & image outline',
					'name' => 'accent_color_separator',
					'type' => 'color_picker',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '50',
						'class' => '',
						'id' => '',
					),
					'default_value' => '#c3a32a',
				),
				array(
					'key' => 'field_5ff4c9aaf375d',
					'label' => 'Page footer color',
					'name' => 'page_footer_color',
					'type' => 'color_picker',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '100',
						'class' => '',
						'id' => '',
					),
					'default_value' => '#483D31',
				),
				array(
					'key' => 'field_5ffb91c1ad78f',
					'label' => 'Page footer text color',
					'name' => 'page_footer_text_color',
					'type' => 'color_picker',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '32',
						'class' => '',
						'id' => '',
					),
					'default_value' => '#ffffff',
				),
				array(
					'key' => 'field_5ffb91f2ad790',
					'label' => 'Page footer text link color',
					'name' => 'page_footer_text_link_color',
					'type' => 'color_picker',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '32',
						'class' => '',
						'id' => '',
					),
					'default_value' => '#faec75',
				),
				array(
					'key' => 'field_5ffb9228ad791',
					'label' => 'Page footer text link hover color',
					'name' => 'page_footer_text_link_hover_color',
					'type' => 'color_picker',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '32',
						'class' => '',
						'id' => '',
					),
					'default_value' => '#ffffff',
				),
			),
		),
		array(
			'key' => 'field_5ff4cbff13392',
			'label' => 'Top Navigation Bar',
			'name' => 'top_navigation_bar_options',
			'type' => 'group',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layout' => 'block',
			'sub_fields' => array(
				array(
					'key' => 'field_5ff4cc3113393',
					'label' => 'Nav item background color',
					'name' => 'nav_item_background_color',
					'type' => 'color_picker',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '25',
						'class' => '',
						'id' => '',
					),
					'default_value' => '#f44b83',
				),
				array(
					'key' => 'field_5ff4cc8713394',
					'label' => 'Nav item text color',
					'name' => 'nav_item_text_color',
					'type' => 'color_picker',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '25',
						'class' => '',
						'id' => '',
					),
					'default_value' => '#ffffff',
				),
				array(
					'key' => 'field_5ff4cca613395',
					'label' => 'Hover background color',
					'name' => 'hover_background_color',
					'type' => 'color_picker',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '25',
						'class' => '',
						'id' => '',
					),
					'default_value' => '#483D31',
				),
				array(
					'key' => 'field_5ff4ccaa13396',
					'label' => 'Hover text color',
					'name' => 'hover_text_color',
					'type' => 'color_picker',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '25',
						'class' => '',
						'id' => '',
					),
					'default_value' => '#ffffff',
				),
				array(
					'key' => 'field_5ff4db6b13397',
					'label' => 'Navigation text size',
					'name' => 'navigation_text_size',
					'type' => 'radio',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '35',
						'class' => '',
						'id' => '',
					),
					'choices' => array(
						'1rem' => 'Normal (Default)',
						'1.2rem' => 'Large',
						'0.8rem' => 'Small',
					),
					'allow_null' => 0,
					'other_choice' => 0,
					'default_value' => '1rem',
					'layout' => 'horizontal',
					'return_format' => 'value',
					'save_other_choice' => 0,
				),
				array(
					'key' => 'field_5ffb92ff7bb1e',
					'label' => 'Navigation text style',
					'name' => 'navigation_text_style',
					'type' => 'radio',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '65',
						'class' => '',
						'id' => '',
					),
					'choices' => array(
						'uppercase' => 'All caps (Default)',
						'capitalize' => 'Capitalize words',
						'lowercase' => 'Lowercase',
						'none' => 'None',
					),
					'allow_null' => 0,
					'other_choice' => 0,
					'default_value' => 'uppercase',
					'layout' => 'horizontal',
					'return_format' => 'value',
					'save_other_choice' => 0,
				),
			),
		),
		array(
			'key' => 'field_5ff4dc2bb571b',
			'label' => 'Typography',
			'name' => 'typography_options',
			'type' => 'group',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layout' => 'block',
			'sub_fields' => array(
				array(
					'key' => 'field_5ff4dd3bb5720',
					'label' => '[coming soon] Body text font',
					'name' => 'body_text_font',
					'type' => 'select',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '80',
						'class' => '',
						'id' => '',
					),
					'choices' => array(
						'Roboto:ital,wght@0,300;0,900;1,300;1,900' => 'Roboto',
						'Work+Sans:ital,wght@0,300;0,800;1,300;1,800' => 'Work Sans',
						'Montserrat:ital,wght@0,300;0,800;1,300;1,800' => 'Montserrat',
						'Poppins:ital,wght@0,300;0,800;1,300;1,800' => 'Poppins',
						'Noto+Serif:ital,wght@0,400;0,700;1,400;1,700' => 'Noto Serif',
						'Cormorant+Garamond:ital,wght@0,500;0,700;1,500;1,700' => 'Cormorant Garamond',
						'Josefin+Slab:ital,wght@0,400;0,700;1,400;1,700' => 'Josefin Slab',
						'Gaegu:wght@400;700' => 'Gaegu',
					),
					'default_value' => false,
					'allow_null' => 0,
					'multiple' => 0,
					'ui' => 0,
					'return_format' => 'array',
					'ajax' => 0,
					'placeholder' => '',
				),
				array(
					'key' => 'field_5ff4dd9ab5721',
					'label' => 'Default text size',
					'name' => 'default_size',
					'type' => 'number',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '20',
						'class' => '',
						'id' => '',
					),
					'default_value' => 19,
					'placeholder' => '',
					'prepend' => '',
					'append' => 'pt',
					'min' => 12,
					'max' => 30,
					'step' => 1,
				),
				array(
					'key' => 'field_5ff4e24dcff0b',
					'label' => '[coming soon!] Heading text font',
					'name' => 'heading_text_font',
					'type' => 'select',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '50',
						'class' => '',
						'id' => '',
					),
					'choices' => array(
						'Roboto:ital,wght@0,100;0,700;1,100;1,700' => 'Roboto',
						'Work+Sans:ital,wght@0,200;0,800;1,200;1,800' => 'Work Sans',
						'Poppins:ital,wght@0,200;0,700;1,200;1,700' => 'Poppins',
						'Barlow+Condensed:ital,wght@0,200;0,700;1,200;1,700' => 'Barlow Condensed',
						'Hind:wght@300;700' => 'Hind',
						'Trispace:wght@200;400;800' => 'Trispace',
						'Cormorant+Garamond:ital,wght@0,300;0,700;1,300;1,700' => 'Cormorant Garamond',
						'Josefin+Slab:ital,wght@0,200;0,700;1,200;1,700' => 'Josefin Slab',
						'Architects+Daughter' => 'Architects Daughter',
						'Gaegu:wght@300;700' => 'Gaegu',
						'Nanum+Pen+Script' => 'Nanum Pen Script',
					),
					'default_value' => false,
					'allow_null' => 0,
					'multiple' => 0,
					'ui' => 0,
					'return_format' => 'value',
					'ajax' => 0,
					'placeholder' => '',
				),
				array(
					'key' => 'field_5ffb95209fb90',
					'label' => '[coming soon!] Tagline text font',
					'name' => 'tagline_text_font',
					'type' => 'select',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '50',
						'class' => '',
						'id' => '',
					),
					'choices' => array(
						'Roboto:ital,wght@0,100;0,700;1,100;1,700' => 'Roboto',
						'Work+Sans:ital,wght@0,200;0,800;1,200;1,800' => 'Work Sans',
						'Poppins:ital,wght@0,200;0,700;1,200;1,700' => 'Poppins',
						'Barlow+Condensed:ital,wght@0,200;0,700;1,200;1,700' => 'Barlow Condensed',
						'Hind:wght@300;700' => 'Hind',
						'Trispace:wght@200;400;800' => 'Trispace',
						'Cormorant+Garamond:ital,wght@0,300;0,700;1,300;1,700' => 'Cormorant Garamond',
						'Josefin+Slab:ital,wght@0,200;0,700;1,200;1,700' => 'Josefin Slab',
						'Architects+Daughter' => 'Architects Daughter',
						'Gaegu:wght@300;700' => 'Gaegu',
						'Nanum+Pen+Script' => 'Nanum Pen Script',
					),
					'default_value' => false,
					'allow_null' => 0,
					'multiple' => 0,
					'ui' => 0,
					'return_format' => 'value',
					'ajax' => 0,
					'placeholder' => '',
				),
			),
		),
		array(
					'key' => 'field_5ff4deb389975',
					'label' => 'Logo colors',
					'name' => 'logo_colors',
					'type' => 'group',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'layout' => 'block',
					'sub_fields' => array(
						array(
							'key' => 'field_5ff4deb389976',
							'label' => 'Birdcage color',
							'name' => 'birdcage_color',
							'type' => 'color_picker',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '25',
								'class' => '',
								'id' => '',
							),
							'default_value' => '#C3A32A',
						),
						array(
							'key' => 'field_5ff4deb389977',
							'label' => 'Branch color',
							'name' => 'branch_color',
							'type' => 'color_picker',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '25',
								'class' => '',
								'id' => '',
							),
							'default_value' => '#483D31',
						),
						array(
							'key' => 'field_5ff4deb389978',
							'label' => 'Bird color, main',
							'name' => 'bird_color_main',
							'type' => 'color_picker',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '25',
								'class' => '',
								'id' => '',
							),
							'default_value' => '#F44B83',
						),
						array(
							'key' => 'field_5ff4deb389979',
							'label' => 'Bird color, secondary',
							'name' => 'bird_color_secondary',
							'type' => 'color_picker',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '25',
								'class' => '',
								'id' => '',
							),
							'default_value' => '#FA7EA0',
						),
						array(
							'key' => 'field_5ffb961258c92',
							'label' => 'Leaves color, main',
							'name' => 'leaves_color_primary',
							'type' => 'color_picker',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '20',
								'class' => '',
								'id' => '',
							),
							'default_value' => '#66CF8D',
						),
						array(
							'key' => 'field_5ffb963658c93',
							'label' => 'Leaves color, darkest',
							'name' => 'leaves_color_dark_01',
							'type' => 'color_picker',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '20',
								'class' => '',
								'id' => '',
							),
							'default_value' => '#336947',
						),
						array(
							'key' => 'field_5ffb965c58c94',
							'label' => 'Leaves color, dark',
							'name' => 'leaves_color_dark_02',
							'type' => 'color_picker',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '20',
								'class' => '',
								'id' => '',
							),
							'default_value' => '#468F61',
						),
						array(
							'key' => 'field_5ffb967e58c95',
							'label' => 'Leaves color, light',
							'name' => 'leaves_color_light',
							'type' => 'color_picker',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '20',
								'class' => '',
								'id' => '',
							),
							'default_value' => '#BDD886',
						),
						array(
							'key' => 'field_5ffb969558c96',
							'label' => 'Leaves color, accent lines',
							'name' => 'leaves_lines',
							'type' => 'color_picker',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '20',
								'class' => '',
								'id' => '',
							),
							'default_value' => '#683FA9',
						),
						array(
							'key' => 'field_5ffb96ce58c97',
							'label' => 'Flower color, main',
							'name' => 'flower_color_main',
							'type' => 'color_picker',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '20',
								'class' => '',
								'id' => '',
							),
							'default_value' => '#DD97C1',
						),
						array(
							'key' => 'field_5ffb971758c98',
							'label' => 'Flower color, darker',
							'name' => 'flower_color_main_darker',
							'type' => 'color_picker',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '20',
								'class' => '',
								'id' => '',
							),
							'default_value' => '#C176AB',
						),
						array(
							'key' => 'field_5ffb974758c99',
							'label' => 'Flower color, light',
							'name' => 'flower_color_light',
							'type' => 'color_picker',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '20',
								'class' => '',
								'id' => '',
							),
							'default_value' => '#F7B5D0',
						),
						array(
							'key' => 'field_5ffb975a58c9a',
							'label' => 'Flower color, lightest',
							'name' => 'flower_color_lightest',
							'type' => 'color_picker',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '20',
								'class' => '',
								'id' => '',
							),
							'default_value' => '#FDF2F3',
						),
						array(
							'key' => 'field_5ffb976b58c9b',
							'label' => 'Flower color, center color',
							'name' => 'flower_color_center_color',
							'type' => 'color_picker',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '20',
								'class' => '',
								'id' => '',
							),
							'default_value' => '#683FA9',
						),
					),
				),

		array (
			'key' => 'field_57fbf37a6e7ea',
			'label' => 'Text',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array (
			'key' => 'field_57f7ceae82de8',
			'label' => 'Contact Info',
			'name' => 'contact_info',
			'type' => 'wysiwyg',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'tabs' => 'all',
			'toolbar' => 'full',
			'media_upload' => 1,
			'delay' => 0,
		),
		array (
			'key' => 'field_57fbf4cf6e7f2',
			'label' => 'Copyright Text',
			'name' => 'copyright_text',
			'type' => 'text',
			'instructions' => 'The text <code>[year]</code> will be replaced with the current year.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => 'Copyright © [year]. All rights reserved.',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array (
			'key' => 'field_57fbf39a6e7eb',
			'label' => 'URLs',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array (
			'key' => 'field_57f7ca2067a98',
			'label' => 'Social Media Links',
			'name' => 'social_links',
			'type' => 'repeater',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'collapsed' => 'field_57f7ca3567a99',
			'min' => 0,
			'max' => 0,
			'layout' => 'row',
			'button_label' => 'Add Service',
			'sub_fields' => array (
				array (
					'key' => 'field_57f7ca3567a99',
					'label' => 'Service',
					'name' => 'service',
					'type' => 'select',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '50',
						'class' => '',
						'id' => '',
					),
					'choices' => array (
						'facebook' => 'Facebook',
						'flickr' => 'Flickr',
						'googleplus' => 'Google+',
						'instagram' => 'Instagram',
						'linkedin' => 'LinkedIn',
						'pinterest' => 'Pinterest',
						'snapchat' => 'Snapchat',
						'tumblr' => 'Tumblr',
						'twitter' => 'Twitter',
						'youtube' => 'YouTube',
					),
					'default_value' => array (
					),
					'allow_null' => 0,
					'multiple' => 0,
					'ui' => 0,
					'ajax' => 0,
					'return_format' => 'value',
					'placeholder' => '',
				),
				array (
					'key' => 'field_57f7cb1267a9b',
					'label' => 'Link Text',
					'name' => 'link_text',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '50',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => 'e.g. "Like us on Facebook", or "@MyOrg"',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array (
					'key' => 'field_57f7caee67a9a',
					'label' => 'URL',
					'name' => 'url',
					'type' => 'url',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '100',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
				),
			),
		),
		array (
			'key' => 'field_57fbf3ab6e7ec',
			'label' => 'Integrations/API Keys',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array (
			'key' => 'field_57f7d17269b71',
			'label' => 'Facebook App ID',
			'name' => 'facebook_app_id',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array (
			'key' => 'field_57f7ca0467a97',
			'label' => 'Google Maps API Key',
			'name' => 'google_maps_api_key',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'options_page',
				'operator' => '==',
				'value' => 'start-site-options',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
	'modified' => 1476826847,
));



endif;

//***************************************   HOMEPAGE HERO
if( function_exists('acf_add_local_field_group') ):

	acf_add_local_field_group(array(
		'key' => 'group_5ffb4910c80e3',
		'title' => 'Homepage Hero',
		'fields' => array(
			array(
				'key' => 'field_5ffb491e4917c',
				'label' => 'Description',
				'name' => '',
				'type' => 'message',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'message' => 'This is space exclusive to the home / first page of your site. This shows one large photo (the "featured image" of this page) with text and buttons positioned over the top of the image. You can edit or turn off any content areas in the settings below.',
				'new_lines' => 'wpautop',
				'esc_html' => 0,
			),
			array(
				'key' => 'field_5ffb4a264917d',
				'label' => 'Large title text',
				'name' => 'large_title_text',
				'type' => 'text',
				'instructions' => 'The main, and largest text over the image. This should be very short!',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key' => 'field_5ffb4b2a4917e',
				'label' => 'Secondary text',
				'name' => 'secondary_text',
				'type' => 'textarea',
				'instructions' => 'This text will show up below the large title text. This should still be pretty short--only a few sentences at most.',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'maxlength' => '',
				'rows' => '',
				'new_lines' => 'wpautop',
			),
			array(
				'key' => 'field_5ffb4ba94917f',
				'label' => 'Call to action button(s)',
				'name' => 'call_to_action_buttons',
				'type' => 'repeater',
				'instructions' => 'You can add up to three "call to action" buttons. These show up under the large and secondary text above. 

There are two types of buttons: a primary button that will most likely be more prominent in design, and a secondary button that will most likely show up more subtle. A third choice is given of a simple text link, which will be less prominent than both.',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'collapsed' => '',
				'min' => 0,
				'max' => 3,
				'layout' => 'row',
				'button_label' => 'Add a button',
				'sub_fields' => array(
					array(
						'key' => 'field_5ffb4ca149180',
						'label' => 'Label',
						'name' => 'cta_label',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => 'Button or link text',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
					),
					array(
						'key' => 'field_5ffb4cd949181',
						'label' => 'Link',
						'name' => 'cta_link',
						'type' => 'link',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'return_format' => 'url',
					),
					array(
						'key' => 'field_5ffb4d2849182',
						'label' => 'Style',
						'name' => 'cta_style',
						'type' => 'radio',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'choices' => array(
							'primary' => 'Primary',
							'secondary' => 'Secondary',
							'text_link' => 'Plain text link',
						),
						'allow_null' => 0,
						'other_choice' => 0,
						'default_value' => '',
						'layout' => 'vertical',
						'return_format' => 'value',
						'save_other_choice' => 0,
					),
				),
			),
			array(
				'key' => 'field_5ffb4da449183',
				'label' => 'Layout options',
				'name' => 'layout_options',
				'type' => 'group',
				'instructions' => 'Below are some options for the layout and size of the hero section',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'layout' => 'block',
				'sub_fields' => array(
					array(
						'key' => 'field_5ffb4df249184',
						'label' => 'Height',
						'name' => 'hero_height',
						'type' => 'radio',
						'instructions' => 'The default is for this hero section to stretch for almost the entire height of your browser screen. If you want this to be shorter/take up less space, set that here',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'choices' => array(
							'full-height' => 'Full height (default)',
							'two-thirds-height' => '2/3 height',
							'one-half-height' => '1/2 height',
						),
						'allow_null' => 0,
						'other_choice' => 0,
						'default_value' => 'full-height',
						'layout' => 'horizontal',
						'return_format' => 'value',
						'save_other_choice' => 0,
					),
					array(
						'key' => 'field_5ffb4ec249185',
						'label' => 'Text position (horizontal)',
						'name' => 'hero_text_position_horizontal',
						'type' => 'radio',
						'instructions' => 'Depending on the featured image, choose which side is best to display the text.',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'choices' => array(
							'left-side' => 'Left side',
							'right-side' => 'Right side',
						),
						'allow_null' => 0,
						'other_choice' => 0,
						'default_value' => 'right-side',
						'layout' => 'horizontal',
						'return_format' => 'value',
						'save_other_choice' => 0,
					),
					array(
						'key' => 'field_5ffb4f9549186',
						'label' => 'Text position (vertical)',
						'name' => 'hero_text_position_vertical',
						'type' => 'radio',
						'instructions' => 'Now what is the best vertical placement?',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'choices' => array(
							'align-top' => 'Near the top',
							'align-middle' => 'In the middle',
							'align-bottom' => 'Near the bottom',
						),
						'allow_null' => 0,
						'other_choice' => 0,
						'default_value' => 'align-middle',
						'layout' => 'horizontal',
						'return_format' => 'value',
						'save_other_choice' => 0,
					),
					array(
						'key' => 'field_5ffb500f49187',
						'label' => 'Text color (optional)',
						'name' => 'hero_text_color',
						'type' => 'color_picker',
						'instructions' => 'If the contrast of the text over your featured image is too light, set a better color for the text here so it will show up clearly over the image.',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '#292929',
					),
					array(
						'key' => 'field_5ffb50c149188',
						'label' => 'Add a background (optional)',
						'name' => 'add_a_background',
						'type' => 'select',
						'instructions' => 'If the text is still hard to read over the image, you can add a semi-transparent background color to the text area. Choose between a light or dark background.',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'choices' => array(
							'bg-none' => 'No background (default)',
							'light-background' => 'Light background',
							'dark-background' => 'Dark background',
						),
						'default_value' => 'bg-none',
						'allow_null' => 0,
						'multiple' => 0,
						'ui' => 0,
						'return_format' => 'value',
						'ajax' => 0,
						'placeholder' => '',
					),
				),
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'page_type',
					'operator' => '==',
					'value' => 'front_page',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'side',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => true,
		'description' => '',
	));

endif;