<?php
/**
 * ACF helper functions
 */

// change / add to the base background choices here
$base_background_options = array (
	'no-background' 		=> 'No background',
	'inverse-background' 	=> 'Inverse',
	'primary-background'	=> 'Primary color background',
);

// grab any accent colors added in the site options with ACF
$acf_color_options = array();
if( get_option( 'options_accent_colors_container_accent_color_array' ) ) :
	$number = get_option( 'options_accent_colors_container_accent_color_array' );
	for ( $i=1; $i<=(int)$number; $i++ ) {
		$acf_color_options[ 'accent-color-' . $i ] = "Accent color #" . $i;
	}
endif;

// now merge those two arrays for all the background options
$background_choices_available = array_merge( $base_background_options, $acf_color_options );


// settings on where the 'sections' are active throughout the site
$where_sections_are_active = array (
	array (
		array (
			'param' => 'post_type',
			'operator' => '==',
			'value' => 'page',
		),
	),
/*	add any additional post types here. 
	array (
		array (
			'param' => 'post_type',
			'operator' => '==',
			'value' => 'person',
		),
	),
*/
);


//***************************************   SITE OPTIONS
if( function_exists('acf_add_local_field_group') ):
acf_add_local_field_group(array (
	'key' => 'group_57f7c88c9aa18',
	'title' => 'Site Options',
	'fields' => array (
		array (
			'key' => 'field_57fbf3676e7e9',
			'label' => 'Display Options',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array(
			'key' => 'field_5a1f1b703a28e',
			'label' => 'Site Logo',
			'name' => 'site_logo',
			'type' => 'image',
			'instructions' => 'Add a logo image for the header. If none, the site name will show in large text.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'url',
			'preview_size' => 'medium',
			'library' => 'all',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => 'jpg, gif, svg, png',
		),
		array (
			'key' => 'field_57f7c92167a96',
			'label' => 'Default Featured Image',
			'name' => 'default_post_thumbnail_id',
			'type' => 'image',
			'instructions' => 'If set, this image will be displayed as the featured image for any posts that don\'t have their own custom featured images.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'id',
			'preview_size' => 'thumbnail',
			'library' => 'all',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
		),
		array (
			'key' => 'field_57fc43235c0d0',
			'label' => 'Excerpt Settings',
			'name' => '',
			'type' => 'message',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => 'Settings below determine how automatically generated post excerpts (aka blurbs) are displayed: how long they should be, and what text (if any) should be appended to the excerpt as a link to the post itself.',
			'new_lines' => 'wpautop',
			'esc_html' => 0,
		),
		array (
			'key' => 'field_57fbf44a6e7f0',
			'label' => 'Length',
			'name' => 'excerpt_length',
			'type' => 'number',
			'instructions' => 'Set to 0 to revert to WordPress\'s default (55 words), or to allow another plugin to trim excerpts.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '40',
				'class' => '',
				'id' => '',
			),
			'default_value' => 40,
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'min' => '',
			'max' => '',
			'step' => '',
		),
		array (
			'key' => 'field_57fbf4686e7f1',
			'label' => 'Units',
			'name' => 'excerpt_length_unit',
			'type' => 'radio',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '20',
				'class' => '',
				'id' => '',
			),
			'choices' => array (
				'words' => 'Words',
				'chars' => 'Characters',
			),
			'allow_null' => 0,
			'other_choice' => 0,
			'save_other_choice' => 0,
			'default_value' => 'words',
			'layout' => 'vertical',
			'return_format' => 'value',
		),
		array (
			'key' => 'field_57fc42c5a2686',
			'label' => 'Link Text',
			'name' => 'excerpt_link_text',
			'type' => 'text',
			'instructions' => 'e.g. \'Read more\'. Leave blank for no link.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '40',
				'class' => '',
				'id' => '',
			),
			'default_value' => 'Read more',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5a1dd45d5edcf',
			'label' => 'Disable page sections on regular pages',
			'name' => 'disable_sections_on_pages',
			'type' => 'true_false',
			'instructions' => 'Check this box to remove the "page sections" editing capabilities on all inside pages of the site. The sections capabilities will then only show up on the front homepage (if a static page is used for the front page) and all inside pages will use the default WordPress page editor.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '100',
				'class' => '',
				'id' => '',
			),
			'message' => 'Use the default WordPress page editor',
			'default_value' => 0,
			'ui' => 0,
			'ui_on_text' => '',
			'ui_off_text' => '',
		),
		array (
			'key' => 'field_5a1d8a764a977',
			'label' => 'Colors',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array (
			'key' => 'field_5a1d8a994a978',
			'label' => 'Base colors',
			'name' => 'base_colors',
			'type' => 'group',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layout' => 'table',
			'sub_fields' => array(
				array(
					'key' => 'field_5a1d8aae4a979',
					'label' => 'Background color',
					'name' => 'background_color',
					'type' => 'color_picker',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '#ffffff',
				),
				array(
					'key' => 'field_5a1d8b844a97a',
					'label' => 'Text color',
					'name' => 'text_color',
					'type' => 'color_picker',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '#565050',
				),
				array(
					'key' => 'field_5a1d8b944a97b',
					'label' => 'Link color',
					'name' => 'link_color',
					'type' => 'color_picker',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '#6D7298',
				),
				array(
					'key' => 'field_5a1d8bf64a97c',
					'label' => 'Link hover',
					'name' => 'link_hover',
					'type' => 'color_picker',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '#565FA3',
				),
			),
		),
		array (
			'key' => 'field_5a1d8e351faec',
			'label' => 'Primary colors',
			'name' => 'primary_colors',
			'type' => 'group',
			'instructions' => 'For use of your main brand color. Text and link colors refer to the text/links on top of the primary brand color',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layout' => 'table',
			'sub_fields' => array(
				array(
					'key' => 'field_5a1d8e351faed',
					'label' => 'Primary color',
					'name' => 'background_color',
					'type' => 'color_picker',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '#FE5F55',
				),
				array(
					'key' => 'field_5a1d8e351faee',
					'label' => 'Text color',
					'name' => 'text_color',
					'type' => 'color_picker',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '#ffffff',
				),
				array(
					'key' => 'field_5a1d8e351faef',
					'label' => 'Link color',
					'name' => 'link_color',
					'type' => 'color_picker',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '#FCE197',
				),
				array(
					'key' => 'field_5a1d8e351faf0',
					'label' => 'Link hover',
					'name' => 'link_hover',
					'type' => 'color_picker',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '#ffffff',
				),
			),
		),
		array (
			'key' => 'field_5a1d90238a9b7',
			'label' => 'Inverse colors',
			'name' => 'inverse_colors',
			'type' => 'group',
			'instructions' => 'For an "inverse" option of the main/base colors.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layout' => 'table',
			'sub_fields' => array(
				array(
					'key' => 'field_5a1d90238a9b8',
					'label' => 'Background color',
					'name' => 'background_color',
					'type' => 'color_picker',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '#565050',
				),
				array(
					'key' => 'field_5a1d90238a9b9',
					'label' => 'Text color',
					'name' => 'text_color',
					'type' => 'color_picker',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '#ffffff',
				),
				array(
					'key' => 'field_5a1d90238a9ba',
					'label' => 'Link color',
					'name' => 'link_color',
					'type' => 'color_picker',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '#B9D8F7',
				),
				array(
					'key' => 'field_5a1d90238a9bb',
					'label' => 'Link hover',
					'name' => 'link_hover',
					'type' => 'color_picker',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '#ffffff',
				),
			),
		),
		array (
			'key' => 'field_5a1d914942cc6',
			'label' => 'Accent colors',
			'name' => 'accent_colors_container',
			'type' => 'group',
			'instructions' => 'Add any additional accent colors',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '100',
				'class' => '',
				'id' => '',
			),
			'layout' => 'block',
			'sub_fields' => array(
				array(
					'key' => 'field_5a1d91aa42cc7',
					'label' => 'All accent colors',
					'name' => 'accent_color_array',
					'type' => 'repeater',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '100',
						'class' => '',
						'id' => '',
					),
					'collapsed' => 'field_5a1d91f142cc9',
					'min' => 0,
					'max' => 0,
					'layout' => 'block',
					'button_label' => 'Add a color',
					'sub_fields' => array(
						array(
							'key' => 'field_5a1d91f142cc9',
							'label' => 'Accent color',
							'name' => 'accent_color',
							'type' => 'color_picker',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '#ffffff',
						),
						array(
							'key' => 'field_5a1d91f142cc8',
							'label' => 'Text',
							'name' => 'accent_color_details',
							'type' => 'group',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '100',
								'class' => '',
								'id' => '',
							),
							'layout' => 'table',
							'sub_fields' => array(
								array(
									'key' => 'field_5a1d91f142cca',
									'label' => 'Text color',
									'name' => 'text_color',
									'type' => 'color_picker',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'default_value' => '#565050',
								),
								array(
									'key' => 'field_5a1d91f142ccb',
									'label' => 'Link color',
									'name' => 'link_color',
									'type' => 'color_picker',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'default_value' => '#6D7298',
								),
								array(
									'key' => 'field_5a1d91f142ccc',
									'label' => 'Link hover',
									'name' => 'link_hover',
									'type' => 'color_picker',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'default_value' => '#565FA3',
								),
							),
						),
					),
				),
			),
		),
		array (
			'key' => 'field_57fbf37a6e7ea',
			'label' => 'Text',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array (
			'key' => 'field_57f7ceae82de8',
			'label' => 'Contact Info',
			'name' => 'contact_info',
			'type' => 'wysiwyg',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'tabs' => 'all',
			'toolbar' => 'full',
			'media_upload' => 1,
			'delay' => 0,
		),
		array (
			'key' => 'field_57fbf4cf6e7f2',
			'label' => 'Copyright Text',
			'name' => 'copyright_text',
			'type' => 'text',
			'instructions' => 'The text <code>[year]</code> will be replaced with the current year.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => 'Copyright © [year]. All rights reserved.',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array (
			'key' => 'field_57fbf39a6e7eb',
			'label' => 'URLs',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array (
			'key' => 'field_57f7ca2067a98',
			'label' => 'Social Media Links',
			'name' => 'social_links',
			'type' => 'repeater',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'collapsed' => 'field_57f7ca3567a99',
			'min' => 0,
			'max' => 0,
			'layout' => 'row',
			'button_label' => 'Add Service',
			'sub_fields' => array (
				array (
					'key' => 'field_57f7ca3567a99',
					'label' => 'Service',
					'name' => 'service',
					'type' => 'select',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '50',
						'class' => '',
						'id' => '',
					),
					'choices' => array (
						'facebook' => 'Facebook',
						'flickr' => 'Flickr',
						'googleplus' => 'Google+',
						'instagram' => 'Instagram',
						'linkedin' => 'LinkedIn',
						'pinterest' => 'Pinterest',
						'snapchat' => 'Snapchat',
						'tumblr' => 'Tumblr',
						'twitter' => 'Twitter',
						'youtube' => 'YouTube',
					),
					'default_value' => array (
					),
					'allow_null' => 0,
					'multiple' => 0,
					'ui' => 0,
					'ajax' => 0,
					'return_format' => 'value',
					'placeholder' => '',
				),
				array (
					'key' => 'field_57f7cb1267a9b',
					'label' => 'Link Text',
					'name' => 'link_text',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '50',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => 'e.g. "Like us on Facebook", or "@MyOrg"',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array (
					'key' => 'field_57f7caee67a9a',
					'label' => 'URL',
					'name' => 'url',
					'type' => 'url',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '100',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
				),
			),
		),
		array (
			'key' => 'field_57fbf3ab6e7ec',
			'label' => 'Integrations/API Keys',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array (
			'key' => 'field_57f7d17269b71',
			'label' => 'Facebook App ID',
			'name' => 'facebook_app_id',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array (
			'key' => 'field_57f7ca0467a97',
			'label' => 'Google Maps API Key',
			'name' => 'google_maps_api_key',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'options_page',
				'operator' => '==',
				'value' => 'start-site-options',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
	'modified' => 1476826847,
));



endif;

//***************************************   HOMEPAGE HERO
if( function_exists('acf_add_local_field_group') ):

	acf_add_local_field_group(array(
		'key' => 'group_5ffb4910c80e3',
		'title' => 'Homepage Hero',
		'fields' => array(
			array(
				'key' => 'field_5ffb491e4917c',
				'label' => 'Description',
				'name' => '',
				'type' => 'message',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'message' => 'This is space exclusive to the home / first page of your site. This shows one large photo (the "featured image" of this page) with text and buttons positioned over the top of the image. You can edit or turn off any content areas in the settings below.',
				'new_lines' => 'wpautop',
				'esc_html' => 0,
			),
			array(
				'key' => 'field_5ffb4a264917d',
				'label' => 'Large title text',
				'name' => 'large_title_text',
				'type' => 'text',
				'instructions' => 'The main, and largest text over the image. This should be very short!',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key' => 'field_5ffb4b2a4917e',
				'label' => 'Secondary text',
				'name' => 'secondary_text',
				'type' => 'textarea',
				'instructions' => 'This text will show up below the large title text. This should still be pretty short--only a few sentences at most.',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'maxlength' => '',
				'rows' => '',
				'new_lines' => 'wpautop',
			),
			array(
				'key' => 'field_5ffb4ba94917f',
				'label' => 'Call to action button(s)',
				'name' => 'call_to_action_buttons',
				'type' => 'repeater',
				'instructions' => 'You can add up to three "call to action" buttons. These show up under the large and secondary text above. 

There are two types of buttons: a primary button that will most likely be more prominent in design, and a secondary button that will most likely show up more subtle. A third choice is given of a simple text link, which will be less prominent than both.',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'collapsed' => '',
				'min' => 0,
				'max' => 3,
				'layout' => 'row',
				'button_label' => 'Add a button',
				'sub_fields' => array(
					array(
						'key' => 'field_5ffb4ca149180',
						'label' => 'Label',
						'name' => 'cta_label',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => 'Button or link text',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
					),
					array(
						'key' => 'field_5ffb4cd949181',
						'label' => 'Link',
						'name' => 'cta_link',
						'type' => 'link',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'return_format' => 'url',
					),
					array(
						'key' => 'field_5ffb4d2849182',
						'label' => 'Style',
						'name' => 'cta_style',
						'type' => 'radio',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'choices' => array(
							'primary' => 'Primary',
							'secondary' => 'Secondary',
							'text_link' => 'Plain text link',
						),
						'allow_null' => 0,
						'other_choice' => 0,
						'default_value' => '',
						'layout' => 'vertical',
						'return_format' => 'value',
						'save_other_choice' => 0,
					),
				),
			),
			array(
				'key' => 'field_5ffb4da449183',
				'label' => 'Layout options',
				'name' => 'layout_options',
				'type' => 'group',
				'instructions' => 'Below are some options for the layout and size of the hero section',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'layout' => 'block',
				'sub_fields' => array(
					array(
						'key' => 'field_5ffb4df249184',
						'label' => 'Height',
						'name' => 'hero_height',
						'type' => 'radio',
						'instructions' => 'The default is for this hero section to stretch for almost the entire height of your browser screen. If you want this to be shorter/take up less space, set that here',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'choices' => array(
							'full-height' => 'Full height (default)',
							'two-thirds-height' => '2/3 height',
							'one-half-height' => '1/2 height',
						),
						'allow_null' => 0,
						'other_choice' => 0,
						'default_value' => 'full-height',
						'layout' => 'horizontal',
						'return_format' => 'value',
						'save_other_choice' => 0,
					),
					array(
						'key' => 'field_5ffb4ec249185',
						'label' => 'Text position (horizontal)',
						'name' => 'hero_text_position_horizontal',
						'type' => 'radio',
						'instructions' => 'Depending on the featured image, choose which side is best to display the text.',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'choices' => array(
							'left-side' => 'Left side',
							'right-side' => 'Right side',
						),
						'allow_null' => 0,
						'other_choice' => 0,
						'default_value' => 'right-side',
						'layout' => 'horizontal',
						'return_format' => 'value',
						'save_other_choice' => 0,
					),
					array(
						'key' => 'field_5ffb4f9549186',
						'label' => 'Text position (vertical)',
						'name' => 'hero_text_position_vertical',
						'type' => 'radio',
						'instructions' => 'Now what is the best vertical placement?',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'choices' => array(
							'align-top' => 'Near the top',
							'align-middle' => 'In the middle',
							'align-bottom' => 'Near the bottom',
						),
						'allow_null' => 0,
						'other_choice' => 0,
						'default_value' => 'align-middle',
						'layout' => 'horizontal',
						'return_format' => 'value',
						'save_other_choice' => 0,
					),
					array(
						'key' => 'field_5ffb500f49187',
						'label' => 'Text color (optional)',
						'name' => 'hero_text_color',
						'type' => 'color_picker',
						'instructions' => 'If the contrast of the text over your featured image is too light, set a better color for the text here so it will show up clearly over the image.',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '#292929',
					),
					array(
						'key' => 'field_5ffb50c149188',
						'label' => 'Add a background (optional)',
						'name' => 'add_a_background',
						'type' => 'select',
						'instructions' => 'If the text is still hard to read over the image, you can add a semi-transparent background color to the text area. Choose between a light or dark background.',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'choices' => array(
							'bg-none' => 'No background (default)',
							'light-background' => 'Light background',
							'dark-background' => 'Dark background',
						),
						'default_value' => 'bg-none',
						'allow_null' => 0,
						'multiple' => 0,
						'ui' => 0,
						'return_format' => 'value',
						'ajax' => 0,
						'placeholder' => '',
					),
				),
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'page_type',
					'operator' => '==',
					'value' => 'front_page',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'side',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => true,
		'description' => '',
	));

endif;